### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'EnumMeta'

### ISSUE THREAD

**Issue by BioSehnsucht** [TitaniumHocker/mount#7]
Trying to use this rather than using subprocess calls to mount/umount, but I am running into an error as soon as I import it.

```python
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mount
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/tmm/storage-manager/venv/lib/python3.9/site-packages/mount/__init__.py", line 1, in <module>
    from .core import mount, umount  # noqa
  File "/opt/tmm/storage-manager/venv/lib/python3.9/site-packages/mount/core.py", line 25, in <module>
    flags: int | MountFlag = 0,
TypeError: unsupported operand type(s) for |: 'type' and 'EnumMeta'
```

This is on a Raspberry Pi 4B, running 64-bit Raspbian, if it matters. Not sure why it's throwing the error since the package is listed for Python 3.9 through 3.11 ... ?

**Comment by BioSehnsucht** [comment]
As a note, I upgraded this Pi to Bookworm Raspbian and now it is using Python 3.11.2 and I am able to import mount without error. So I am guessing perhaps the 3.9.x should perhaps not be listed as supported?

**Comment by TitaniumHocker** [comment]
Yes, 3.9 doesn't support such operations. I'll remove 3.9 from supported versions.
Thx for the issue
